version: '3'

services:
  db:
    container_name: db
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: postgres
      POSTGRES_DB: nodedocker
    networks:
      - nodedocker  
    ports:
      - "5435:5432"  

  app:
    container_name: app
    build: .
    ports:
     - "8080:8080" 
    env_file:
      - .env
    networks:
      - nodedocker  
      
networks:
  nodedocker:
    driver: bridge

